-- create.sql (DB 초기화용)
DROP DATABASE IF EXISTS playground;


CREATE DATABASE playground;


USE playground;


DROP TABLE IF EXISTS ANIMAL_INS;


CREATE TABLE
    ANIMAL_INS (
        ANIMAL_ID VARCHAR(255) NOT NULL,
        ANIMAL_TYPE VARCHAR(255) NOT NULL,
        DATETIME DATETIME NOT NULL,
        INTAKE_CONDITION VARCHAR(255) NOT NULL,
        NAME VARCHAR(255),
        SEX_UPON_INTAKE VARCHAR(255) NOT NULL
    );