-- create.sql (DB 초기화용)
DROP DATABASE IF EXISTS playground;


CREATE DATABASE playground;


USE playground;


DROP TABLE IF EXISTS DEVELOPER_INFOS;


CREATE TABLE
    DEVELOPER_INFOS (
        ID VARCHAR(255) UNIQUE NOT NULL,
        FIRST_NAME VARCHAR(255),
        LAST_NAME VARCHAR(255),
        EMAIL VARCHAR(255) UNIQUE NOT NULL,
        SKILL_1 VARCHAR(255),
        SKILL_2 VARCHAR(255),
        SKILL_3 VARCHAR(255)
    );