-- create.sql (DB 초기화용)
DROP DATABASE IF EXISTS playground;


CREATE DATABASE playground;


USE playground;


DROP TABLE IF EXISTS USER_INFO;


CREATE TABLE
    USER_INFO (USER_ID INTEGER NOT NULL, GENDER TINYINT, AGE INTEGER, JOINED DATE NOT NULL);