-- create.sql (DB 초기화용)
DROP DATABASE IF EXISTS playground;

CREATE DATABASE playground;

USE playground;

DROP TABLE IF EXISTS USED_GOODS_BOARD;

DROP TABLE IF EXISTS USED_GOODS_REPLY;

CREATE TABLE
    USED_GOODS_BOARD (
        BOARD_ID VARCHAR(5) PRIMARY KEY,
        WRITER_ID VARCHAR(50) NOT NULL,
        TITLE VARCHAR(100) NOT NULL,
        CONTENTS VARCHAR(1000) NOT NULL,
        PRICE INT NOT NULL,
        CREATED_DATE DATE NOT NULL,
        STATUS VARCHAR(10) NOT NULL,
        VIEWS INT NOT NULL
    );

CREATE TABLE
    USED_GOODS_REPLY (
        REPLY_ID VARCHAR(10) PRIMARY KEY,
        BOARD_ID VARCHAR(5) NOT NULL,
        WRITER_ID VARCHAR(50) NOT NULL,
        CONTENTS VARCHAR(1000),
        CREATED_DATE DATE NOT NULL
    );