-- create_tables.sql
DROP TABLE IF EXISTS USED_GOODS_BOARD;

CREATE TABLE USED_GOODS_BOARD (
    BOARD_ID TEXT PRIMARY KEY,
    WRITER_ID TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENTS TEXT NOT NULL,
    PRICE INTEGER NOT NULL,
    CREATED_DATE TEXT NOT NULL, -- SQLite는 TEXT로 날짜 저장
    STATUS TEXT NOT NULL,
    VIEWS INTEGER NOT NULL
);

DROP TABLE IF EXISTS USED_GOODS_REPLY;

CREATE TABLE USED_GOODS_REPLY (
    REPLY_ID TEXT PRIMARY KEY,
    BOARD_ID TEXT NOT NULL,
    WRITER_ID TEXT NOT NULL,
    CONTENTS TEXT,
    CREATED_DATE TEXT NOT NULL
);